---
# tasks file for role/maas

- name: "maass_task | Upload Provision example Ceph juju bundle"
  copy:
    src: "./roles/juju/files/ceph/bundle.yaml"
    dest: "/home/{{NODE_SSH_USER}}/.local/share/juju/bundle.yaml"
    owner: "{{NODE_SSH_USER}}"
    group: "{{NODE_SSH_USER}}"
    mode: '0600'
  when: NODE_SSH_USER != 'root'
  tags:
    - maass_task
