---
# tasks file for role/maas
# This is based on https://maas.io/docs/snap/3.2/ui/maas-installation

- name: "maass_task | Set up Juju"
  ansible.builtin.script:
    cmd: "./roles/juju/scripts/030-setup-juju.sh {{NODE_SSH_USER}}"