---
# tasks file for role/maas

- name: generate SSH key "{{NODE_SSH_USER}}"
  user:
    name: "{{NODE_SSH_USER}}"
    generate_ssh_key: yes
    ssh_key_type: rsa
    ssh_key_bits: 4096
    ssh_key_file: .ssh/{{SSH_KEY_FILENAME}}
    force: no