---
# tasks file for role/maas

- name: "install_task | Update repositories cache"
  apt:
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: "install_task | Update all packages to their latest version"
  apt:
    name: "*"
    state: latest
  when: ansible_os_family == "Debian"

- name: "install_task | packages"
  apt: name={{item}} state=present
  with_items:
    - wget
    - nano
    - snap

- name: "install_task | snap juju"
  community.general.snap:
    name:
      - juju
      - charm
    classic: yes

- name: "install_task | snap jq"
  community.general.snap:
    name:
      - jq
    classic: yes

- name: "install_task | snap maas"
  community.general.snap:
    name:
      - maas
    channel: 3.2/stable

- name: generate SSH key "{{node_ssh_user}}"
  user:
    name: "{{node_ssh_user}}"
    generate_ssh_key: yes
    ssh_key_type: rsa
    ssh_key_bits: 4096
    ssh_key_file: .ssh/{{ssh_key_filename}}
    force: no