---
# tasks file for role/maas

- name: "storage_task | Upload Provision example Ceph juju bundle"
  copy:
    src: "./roles/maas/files/ceph/bundle.yaml"
    dest: "/home/{{NODE_SSH_USER}}/job/{{ceph_template_credentials_name}}"
    owner: "{{NODE_SSH_USER}}"
    group: "{{NODE_SSH_USER}}"
    mode: '0600'
  when: NODE_SSH_USER != 'root'
  tags:
    - storage_task
