---
# tasks file for role/maas

- name: "pre_task | Add IP address of all hosts to all hosts"
  lineinfile:
    dest: /etc/hosts
    regexp: '.*{{item}}$'
    line: "{{hostvars[item].ansible_host}} {{item}}.seasolutions.com.br"
    state: present
  when: hostvars[item].ansible_host is defined
  with_items: "{{groups.all}}"

- name: "pre_task | Ensure that ssh directory for host's private SSH key"
  file:
    path: "/var/snap/maas/current/root/.ssh"
    state: directory
  tags:
    - pre_task

- name: "pre_task | Upload private ssh key id_rsa"
  copy:
    src: "/home/{{ NODE_SSH_USER }}/{{NODE_SOURCE_SSH_KEYFILE}}"
    dest: "/var/snap/maas/current/root/.ssh/"
    owner: root
    group: root
    mode: '0400'
    remote_src: yes
  tags:
    - pre_task
  become: yes
