---
# tasks file for role/maas

- name: "install_task | packages"
  apt: name={{item}} state=present
  with_items:
    - wget
    - nano
    - snap
    - postgresql

- name: "install_task | snap juju"
  community.general.snap:
    name:
      - juju
      - charm
    classic: yes

- name: "install_task | snap jq"
  community.general.snap:
    name:
      - jq
    classic: yes

- name: "install_task | snap maas"
  community.general.snap:
    name:
      - maas
    channel: 3.2/stable