---
# tasks file for roles/maas
- name: "main | Include host configs"
  include_tasks: "configs.yml"

- name: "main | Include maas configs"
  include_tasks: "maas.yml"

- name: "main | Include maas configs host libvirt"
  include_tasks: "maas-libvirt-host.yml"

    # - name: "main | Include ceph bundle of juju"
    #   include_tasks: "ceph.yml"

    # - name: "main | Include openstack bundle of juju"
    #   include_tasks: "openstack.yml"